apiVersion: v2
version: 0.41.0
appVersion: "v0.41.0"
kubeVersion: ">=1.22.0-0"
type: application
name: flux-instance
description: |
  A Helm chart for deploying a Flux instance managed by Flux Operator.
home: https://fluxoperator.dev
icon: https://raw.githubusercontent.com/cncf/artwork/main/projects/flux/icon/color/flux-icon-color.png
sources:
  - https://github.com/controlplaneio-fluxcd/flux-operator
  - https://github.com/controlplaneio-fluxcd/charts
annotations:
  "artifacthub.io/license": AGPL-3.0
  "artifacthub.io/links": |
    - name: Documentation
      url: https://fluxoperator.dev/docs
    - name: Chart Source
      url: https://github.com/controlplaneio-fluxcd/charts
    - name: Upstream Project
      url: https://github.com/controlplaneio-fluxcd/flux-operator
maintainers:
  - name: ControlPlane Flux Team
    email: flux-enterprise@control-plane.io
keywords:
  - flux
  - fluxcd
  - gitops
