name: e2e

on:
  push:
    branches: ['*']

permissions:
  contents: read

jobs:
  upgrade-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Helm
        uses: azure/setup-helm@v4.3.1
      - name: Setup Flux Operator CLI
        uses: controlplaneio-fluxcd/flux-operator/actions/setup@v0.41.1
      - name: Setup Kubernetes Kind
        uses: helm/kind-action@v1.13.0
      - name: Install latest stable
        run: |
          helm install flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator \
          --namespace flux-system \
          --create-namespace \
          --wait
      - name: Upgrade to current
        run: |
          helm upgrade flux-operator ./charts/flux-operator \
          --namespace flux-system \
          --wait
      - name: Deploy flux instance
        run: |
          helm install flux ./charts/flux-instance \
          --namespace flux-system \
          --set healthcheck.enabled=true \
          --wait
      - name: Check version
        run: |
          flux-operator version
